import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:permission_handler/permission_handler.dart';
import '../../../theme/linlink_theme.dart';
import '../../pairing/pairing_service.dart';
import '../bloc/camera_bloc.dart';
import '../bloc/camera_event.dart';
import '../bloc/camera_state.dart';

class ScannerScreen extends StatelessWidget {
  const ScannerScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => CameraBloc()..add(const CameraInitializeRequested()),
      child: const _ScannerView(),
    );
  }
}

class _ScannerView extends StatelessWidget {
  const _ScannerView();

  @override
  Widget build(BuildContext context) {
    final cameraBloc = context.read<CameraBloc>();

    return Scaffold(
      backgroundColor: LinLinkColors.background,
      body: SafeArea(
        child: BlocConsumer<CameraBloc, CameraState>(
          listener: (context, state) {
            if (state.status == CameraStatus.scanned && state.scannedData != null) {
              _handleScannedData(context, state.scannedData!);
            }
          },
          builder: (context, state) {
            return Stack(
              children: [
                // Camera viewfinder or fallback
                Positioned.fill(
                  child: _buildCameraContent(context, state),
                ),

                // Top app bar
                Positioned(
                  top: 12,
                  left: 16,
                  right: 16,
                  child: Row(
                    children: [
                      IconButton(
                        style: IconButton.styleFrom(
                          backgroundColor: LinLinkColors.surfaceContainer.withAlpha(220),
                          foregroundColor: LinLinkColors.onSurface,
                        ),
                        icon: const Icon(Icons.arrow_back),
                        onPressed: () => Navigator.of(context).pop(),
                        tooltip: 'Back',
                      ),
                      const SizedBox(width: 12),
                      const Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Scan Linux QR',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.bold,
                                color: LinLinkColors.onSurface,
                              ),
                            ),
                            Text(
                              'Point at the code generated by `linlink pair`',
                              style: TextStyle(
                                fontSize: 12,
                                color: LinLinkColors.onSurfaceVariant,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),

                // Bottom Controls (Terminal snippet, Torch & Manual IP)
                Positioned(
                  bottom: 24,
                  left: 20,
                  right: 20,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      // Terminal command card
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
                        decoration: BoxDecoration(
                          color: LinLinkColors.surfaceContainer.withAlpha(235),
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(color: LinLinkColors.outlineVariant),
                        ),
                        child: Row(
                          children: [
                            const Icon(
                              Icons.terminal,
                              color: LinLinkColors.primary,
                              size: 18,
                            ),
                            const SizedBox(width: 10),
                            const Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    'RUN ON YOUR WORKSTATION',
                                    style: TextStyle(
                                      fontSize: 10,
                                      fontWeight: FontWeight.w600,
                                      letterSpacing: 0.8,
                                      color: LinLinkColors.onSurfaceVariant,
                                    ),
                                  ),
                                  SizedBox(height: 1),
                                  Text(
                                    'linlink pair',
                                    style: TextStyle(
                                      fontSize: 13,
                                      fontFamily: 'monospace',
                                      fontWeight: FontWeight.w600,
                                      color: LinLinkColors.onSurface,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            IconButton(
                              icon: const Icon(Icons.copy, size: 16),
                              color: LinLinkColors.primary,
                              tooltip: 'Copy command',
                              onPressed: () {
                                Clipboard.setData(const ClipboardData(text: 'linlink pair'));
                                ScaffoldMessenger.of(context).showSnackBar(
                                  const SnackBar(
                                    content: Text('Copied "linlink pair" to clipboard'),
                                  ),
                                );
                              },
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 12),

                      // Torch and manual IP actions
                      Row(
                        children: [
                          Expanded(
                            child: BlocBuilder<CameraBloc, CameraState>(
                              buildWhen: (prev, curr) => prev.isTorchOn != curr.isTorchOn,
                              builder: (context, state) {
                                return OutlinedButton.icon(
                                  style: OutlinedButton.styleFrom(
                                    backgroundColor: LinLinkColors.surfaceContainer.withAlpha(220),
                                    foregroundColor: state.isTorchOn
                                        ? LinLinkColors.primary
                                        : LinLinkColors.onSurface,
                                    side: BorderSide(
                                      color: state.isTorchOn
                                          ? LinLinkColors.primary
                                          : LinLinkColors.outlineVariant,
                                    ),
                                    padding: const EdgeInsets.symmetric(vertical: 13),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                  icon: Icon(
                                    state.isTorchOn
                                        ? Icons.flashlight_on
                                        : Icons.flashlight_off,
                                    size: 18,
                                  ),
                                  label: Text(
                                    state.isTorchOn ? 'Torch On' : 'Torch Off',
                                    style: const TextStyle(fontWeight: FontWeight.w600),
                                  ),
                                  onPressed: () =>
                                      cameraBloc.add(const CameraToggleTorchRequested()),
                                );
                              },
                            ),
                          ),
                          const SizedBox(width: 10),
                          Expanded(
                            child: FilledButton.icon(
                              style: FilledButton.styleFrom(
                                backgroundColor: LinLinkColors.primary,
                                foregroundColor: LinLinkColors.onPrimary,
                                padding: const EdgeInsets.symmetric(vertical: 13),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(10),
                                ),
                              ),
                              icon: const Icon(Icons.lan_outlined, size: 18),
                              label: const Text(
                                'Manual IP',
                                style: TextStyle(fontWeight: FontWeight.w600),
                              ),
                              onPressed: () => _showManualEntryDialog(context),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ],
            );
          },
        ),
      ),
    );
  }

  Widget _buildCameraContent(BuildContext context, CameraState state) {
    final cameraBloc = context.read<CameraBloc>();

    if (state.status == CameraStatus.permissionRequesting) {
      return const Center(
        child: CircularProgressIndicator(color: LinLinkColors.primary),
      );
    }

    if (state.status == CameraStatus.permissionDenied ||
        state.status == CameraStatus.permissionPermanentlyDenied) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.all(28.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Container(
                width: 64,
                height: 64,
                decoration: BoxDecoration(
                  color: LinLinkColors.surfaceContainerHigh,
                  borderRadius: BorderRadius.circular(16),
                ),
                child: const Icon(
                  Icons.no_photography_outlined,
                  size: 32,
                  color: LinLinkColors.outline,
                ),
              ),
              const SizedBox(height: 18),
              const Text(
                'Camera Access Needed',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: LinLinkColors.onSurface,
                ),
              ),
              const SizedBox(height: 8),
              const Text(
                'Camera permission is required to scan the pairing QR code from your Linux terminal.',
                textAlign: TextAlign.center,
                style: TextStyle(
                  color: LinLinkColors.onSurfaceVariant,
                  fontSize: 13,
                  height: 1.4,
                ),
              ),
              const SizedBox(height: 20),
              FilledButton(
                onPressed: () => state.status == CameraStatus.permissionPermanentlyDenied
                    ? openAppSettings()
                    : cameraBloc.add(const CameraInitializeRequested()),
                child: const Text('Grant Camera Access'),
              ),
              const SizedBox(height: 10),
              TextButton.icon(
                icon: const Icon(Icons.keyboard_outlined, size: 18),
                label: const Text('Enter Connection Manually'),
                onPressed: () => _showManualEntryDialog(context),
              ),
            ],
          ),
        ),
      );
    }

    return Stack(
      children: [
        MobileScanner(
          controller: cameraBloc.scannerController,
          errorBuilder: (context, error) {
            return Center(
              child: Padding(
                padding: const EdgeInsets.all(24.0),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    const Icon(Icons.videocam_off_outlined, size: 48, color: LinLinkColors.error),
                    const SizedBox(height: 12),
                    const Text(
                      'Camera Initialisation Error',
                      style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: LinLinkColors.onSurface),
                    ),
                    const SizedBox(height: 6),
                    Text(
                      error.errorDetails?.message ?? 'Could not initialize camera preview on this device.',
                      textAlign: TextAlign.center,
                      style: const TextStyle(fontSize: 12, color: LinLinkColors.onSurfaceVariant),
                    ),
                    const SizedBox(height: 18),
                    FilledButton.icon(
                      icon: const Icon(Icons.lan_outlined, size: 18),
                      label: const Text('Enter Connection Manually'),
                      onPressed: () => _showManualEntryDialog(context),
                    ),
                  ],
                ),
              ),
            );
          },
          onDetect: (capture) {
            for (final barcode in capture.barcodes) {
              final raw = barcode.rawValue ?? barcode.displayValue;
              if (raw != null && raw.trim().isNotEmpty) {
                cameraBloc.add(CameraBarcodeScanned(raw.trim()));
                break;
              }
            }
          },
        ),

        // Clean framed reticle cutout overlay
        Center(
          child: SizedBox(
            width: 260,
            height: 260,
            child: Stack(
              children: [
                // Clean viewfinder boundary
                Container(
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(
                      color: LinLinkColors.primary.withAlpha(180),
                      width: 2,
                    ),
                  ),
                ),

                // Subtle corner markers
                const _ViewfinderCorners(),

                // Instruction label
                Positioned(
                  bottom: 14,
                  left: 0,
                  right: 0,
                  child: Center(
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 5),
                      decoration: BoxDecoration(
                        color: LinLinkColors.background.withAlpha(200),
                        borderRadius: BorderRadius.circular(8),
                        border: Border.all(color: LinLinkColors.outlineVariant),
                      ),
                      child: const Text(
                        'Align QR code within frame',
                        style: TextStyle(
                          fontSize: 11,
                          fontWeight: FontWeight.w500,
                          color: LinLinkColors.onSurface,
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  void _handleScannedData(BuildContext context, String payload) {
    final cameraBloc = context.read<CameraBloc>();
    final target = PairingTarget.tryParse(payload);

    if (target == null) {
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (dialogCtx) => AlertDialog(
          backgroundColor: LinLinkColors.surfaceContainer,
          title: const Row(
            children: [
              Icon(Icons.warning_amber_rounded, color: LinLinkColors.warning),
              SizedBox(width: 8),
              Text('Unrecognized QR'),
            ],
          ),
          content: Text(
            'The scanned text is not a valid LinLink pairing payload:\n"$payload"\n\n'
            'Please run `linlink pair` in your Linux terminal to generate a valid code.',
            style: const TextStyle(color: LinLinkColors.onSurfaceVariant),
          ),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.of(dialogCtx).pop();
                _showManualEntryDialog(context);
              },
              child: const Text('Enter Manually'),
            ),
            FilledButton(
              onPressed: () {
                Navigator.of(dialogCtx).pop();
                cameraBloc.add(const CameraResetScanRequested());
              },
              child: const Text('Scan Again'),
            ),
          ],
        ),
      );
      return;
    }

    // Detect P2P file transfer QR (mode=p2p)
    final isP2P = payload.contains('mode=p2p');
    if (isP2P) {
      _startP2PReceive(context, target);
      return;
    }

    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (dialogCtx) => _PairingConfirmDialog(
        target: target,
        onSuccess: (companion) {
          Navigator.of(dialogCtx).pop();
          Navigator.of(context).pop(companion);
        },
        onCancel: () {
          Navigator.of(dialogCtx).pop();
          cameraBloc.add(const CameraResetScanRequested());
        },
      ),
    );
  }

  /// P2P receive flow: connect to sender, list queued files, and download them all.
  void _startP2PReceive(BuildContext context, PairingTarget target) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (dialogCtx) => _P2PReceiveDialog(
        target: target,
        onComplete: (int count) {
          Navigator.of(dialogCtx).pop();
          Navigator.of(context).pop(); // Return to home
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              backgroundColor: LinLinkColors.secondaryContainer,
              duration: const Duration(seconds: 4),
              content: Row(
                children: [
                  const Icon(Icons.download_done, color: LinLinkColors.secondary),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      '📥 Received $count file${count > 1 ? 's' : ''}\nSaved in Downloads/LinLink',
                      style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 12),
                    ),
                  ),
                ],
              ),
            ),
          );
        },
        onCancel: () {
          Navigator.of(dialogCtx).pop();
          context.read<CameraBloc>().add(const CameraResetScanRequested());
        },
      ),
    );
  }

  void _showManualEntryDialog(BuildContext context) {
    final hostController = TextEditingController();
    final portController = TextEditingController(text: '7878');
    final tokenController = TextEditingController();
    final nameController = TextEditingController(text: 'Android Phone');

    showDialog(
      context: context,
      builder: (dialogCtx) => AlertDialog(
        backgroundColor: LinLinkColors.surfaceContainer,
        title: const Row(
          children: [
            Icon(Icons.lan_outlined, color: LinLinkColors.primary),
            SizedBox(width: 10),
            Text('Manual Pairing'),
          ],
        ),
        content: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Enter the IP and session token printed by `linlink pair` on your Linux host:',
                style: TextStyle(fontSize: 12, color: LinLinkColors.onSurfaceVariant),
              ),
              const SizedBox(height: 14),
              TextField(
                controller: hostController,
                decoration: const InputDecoration(
                  labelText: 'Linux IP / Host (or full URL)',
                  hintText: '192.168.1.50 or 10.0.0.5',
                ),
              ),
              const SizedBox(height: 10),
              TextField(
                controller: portController,
                keyboardType: TextInputType.number,
                decoration: const InputDecoration(
                  labelText: 'Port',
                  hintText: '7878',
                ),
              ),
              const SizedBox(height: 10),
              TextField(
                controller: tokenController,
                decoration: const InputDecoration(
                  labelText: 'Session Token (or full URL)',
                  hintText: 'e.g. 31327e36 or linlink://...',
                ),
              ),
              const SizedBox(height: 10),
              TextField(
                controller: nameController,
                decoration: const InputDecoration(
                  labelText: 'Device Name (shown on Linux)',
                  hintText: 'Pixel 8',
                ),
              ),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogCtx).pop(),
            child: const Text('Cancel'),
          ),
          FilledButton(
            onPressed: () {
              final rawHost = hostController.text.trim();
              final rawToken = tokenController.text.trim();
              final targetFromToken = PairingTarget.tryParse(rawToken);
              final targetFromHost = PairingTarget.tryParse(rawHost);

              final effectiveTarget = targetFromToken ??
                  targetFromHost ??
                  PairingTarget(
                    host: rawHost,
                    port: int.tryParse(portController.text.trim()) ?? 7878,
                    token: rawToken,
                  );

              if (effectiveTarget.token.isEmpty || effectiveTarget.host.isEmpty) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('Please enter host and token (or paste URL).')),
                );
                return;
              }

              Navigator.of(dialogCtx).pop();

              showDialog(
                context: context,
                barrierDismissible: false,
                builder: (confirmCtx) => _PairingConfirmDialog(
                  target: effectiveTarget,
                  onSuccess: (companion) {
                    Navigator.of(confirmCtx).pop();
                    Navigator.of(context).pop(companion);
                  },
                  onCancel: () => Navigator.of(confirmCtx).pop(),
                ),
              );
            },
            child: const Text('Proceed'),
          ),
        ],
      ),
    );
  }
}

class _ViewfinderCorners extends StatelessWidget {
  const _ViewfinderCorners();

  @override
  Widget build(BuildContext context) {
    const stroke = 3.5;
    const len = 20.0;
    const color = LinLinkColors.primary;

    return Stack(
      children: [
        // Top-Left
        Positioned(
          top: 0,
          left: 0,
          child: Container(width: len, height: stroke, color: color),
        ),
        Positioned(
          top: 0,
          left: 0,
          child: Container(width: stroke, height: len, color: color),
        ),

        // Top-Right
        Positioned(
          top: 0,
          right: 0,
          child: Container(width: len, height: stroke, color: color),
        ),
        Positioned(
          top: 0,
          right: 0,
          child: Container(width: stroke, height: len, color: color),
        ),

        // Bottom-Left
        Positioned(
          bottom: 0,
          left: 0,
          child: Container(width: len, height: stroke, color: color),
        ),
        Positioned(
          bottom: 0,
          left: 0,
          child: Container(width: stroke, height: len, color: color),
        ),

        // Bottom-Right
        Positioned(
          bottom: 0,
          right: 0,
          child: Container(width: len, height: stroke, color: color),
        ),
        Positioned(
          bottom: 0,
          right: 0,
          child: Container(width: stroke, height: len, color: color),
        ),
      ],
    );
  }
}

class _PairingConfirmDialog extends StatefulWidget {
  final PairingTarget target;
  final ValueChanged<PairedCompanion> onSuccess;
  final VoidCallback onCancel;

  const _PairingConfirmDialog({
    required this.target,
    required this.onSuccess,
    required this.onCancel,
  });

  @override
  State<_PairingConfirmDialog> createState() => _PairingConfirmDialogState();
}

class _PairingConfirmDialogState extends State<_PairingConfirmDialog> {
  late final TextEditingController _nameController;
  bool _isLinking = false;
  String? _errorMessage;

  @override
  void initState() {
    super.initState();
    String defaultName = 'Android Phone';
    if (Platform.isLinux) {
      defaultName = 'Linux Client';
    } else if (Platform.isMacOS) {
      defaultName = 'Mac Client';
    } else if (Platform.isWindows) {
      defaultName = 'Windows Client';
    } else if (Platform.isIOS) {
      defaultName = 'iPhone';
    }
    _nameController = TextEditingController(text: defaultName);
  }

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  Future<void> _startPairing() async {
    final name =
        _nameController.text.trim().isEmpty ? 'Android Device' : _nameController.text.trim();

    setState(() {
      _isLinking = true;
      _errorMessage = null;
    });

    try {
      final companion = await PairingService.pair(
        target: widget.target,
        deviceName: name,
      );
      if (mounted) {
        widget.onSuccess(companion);
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _isLinking = false;
          _errorMessage = e.toString().replaceFirst('Exception: ', '');
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      backgroundColor: LinLinkColors.surfaceContainer,
      title: const Row(
        children: [
          Icon(Icons.phonelink_setup, color: LinLinkColors.primary),
          SizedBox(width: 10),
          Text('Confirm Connection'),
        ],
      ),
      content: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Linux Companion Target:',
              style: TextStyle(
                color: LinLinkColors.onSurfaceVariant,
                fontSize: 12,
                fontWeight: FontWeight.w500,
              ),
            ),
            const SizedBox(height: 8),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: LinLinkColors.surfaceContainerLow,
                borderRadius: BorderRadius.circular(10),
                border: Border.all(color: LinLinkColors.outlineVariant),
              ),
              child: Row(
                children: [
                  Container(
                    width: 36,
                    height: 36,
                    decoration: BoxDecoration(
                      color: LinLinkColors.surfaceContainerHigh,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: const Icon(
                      Icons.desktop_windows,
                      size: 20,
                      color: LinLinkColors.primary,
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          '${widget.target.host}:${widget.target.port}',
                          style: const TextStyle(
                            fontWeight: FontWeight.w600,
                            fontSize: 13,
                            fontFamily: 'monospace',
                            color: LinLinkColors.onSurface,
                          ),
                        ),
                        const SizedBox(height: 2),
                        Text(
                          'Token: ${widget.target.token}',
                          style: const TextStyle(
                            color: LinLinkColors.onSurfaceVariant,
                            fontSize: 11,
                            fontFamily: 'monospace',
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 14),
            const Text(
              'Device Name (shown on Linux):',
              style: TextStyle(fontSize: 12, color: LinLinkColors.onSurfaceVariant),
            ),
            const SizedBox(height: 6),
            TextField(
              controller: _nameController,
              enabled: !_isLinking,
              decoration: const InputDecoration(
                hintText: 'e.g. Pixel 8',
              ),
            ),
            if (_isLinking) ...[
              const SizedBox(height: 20),
              const Center(
                child: Column(
                  children: [
                    SizedBox(
                      width: 24,
                      height: 24,
                      child: CircularProgressIndicator(
                        strokeWidth: 2.5,
                        color: LinLinkColors.primary,
                      ),
                    ),
                    SizedBox(height: 10),
                    Text(
                      'Linking with Linux Companion…',
                      style: TextStyle(fontSize: 13, color: LinLinkColors.primary),
                    ),
                  ],
                ),
              ),
            ],
            if (_errorMessage != null) ...[
              const SizedBox(height: 14),
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: LinLinkColors.errorContainer.withAlpha(50),
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: LinLinkColors.error.withAlpha(80)),
                ),
                child: Row(
                  children: [
                    const Icon(Icons.error_outline, color: LinLinkColors.error, size: 18),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        _errorMessage!,
                        style: const TextStyle(color: LinLinkColors.error, fontSize: 12),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ],
        ),
      ),
      actions: [
        if (!_isLinking) ...[
          TextButton(
            onPressed: widget.onCancel,
            child: const Text('Cancel'),
          ),
          FilledButton.icon(
            icon: const Icon(Icons.link, size: 18),
            label: const Text('Link Now'),
            onPressed: _startPairing,
          ),
        ],
      ],
    );
  }
}

/// Dialog that handles P2P file receiving — connects to sender's queued files
/// and downloads them one-by-one to Downloads/LinLink.
class _P2PReceiveDialog extends StatefulWidget {
  final PairingTarget target;
  final void Function(int count) onComplete;
  final VoidCallback onCancel;

  const _P2PReceiveDialog({
    required this.target,
    required this.onComplete,
    required this.onCancel,
  });

  @override
  State<_P2PReceiveDialog> createState() => _P2PReceiveDialogState();
}

class _P2PReceiveDialogState extends State<_P2PReceiveDialog> {
  String _statusMessage = 'Connecting to sender...';
  String? _errorMessage;
  int _totalFiles = 0;
  int _downloadedFiles = 0;
  String _currentFileName = '';

  @override
  void initState() {
    super.initState();
    _startReceiving();
  }

  Future<void> _startReceiving() async {
    setState(() {
      _errorMessage = null;
      _statusMessage = 'Connecting to sender...';
    });

    final baseUrl = 'http://${widget.target.host}:${widget.target.port}';
    final token = widget.target.token;
    final client = HttpClient()..connectionTimeout = const Duration(seconds: 10);

    try {
      // 1. Fetch file list from sender
      final listUri = Uri.parse('$baseUrl/p2p/files?t=$token');
      final listReq = await client.getUrl(listUri);
      final listRes = await listReq.close();
      final listBody = await listRes.transform(utf8.decoder).join();
      final listData = jsonDecode(listBody) as Map<String, dynamic>;

      if (listData['status'] != 'ok') {
        throw Exception(listData['message'] ?? 'Failed to get file list');
      }

      final files = (listData['files'] as List<dynamic>?) ?? [];
      if (files.isEmpty) {
        throw Exception('No files queued on sender');
      }

      setState(() {
        _totalFiles = files.length;
        _statusMessage = 'Downloading ${files.length} file${files.length > 1 ? 's' : ''}...';
      });

      // 2. Ensure target directory exists
      final destDir = Directory('/storage/emulated/0/Download/LinLink');
      if (!await destDir.exists()) {
        await destDir.create(recursive: true);
      }

      // 3. Download each file
      for (int i = 0; i < files.length; i++) {
        final fileInfo = files[i] as Map<String, dynamic>;
        final fileName = fileInfo['name'] as String? ?? 'file_$i';
        final fileIndex = fileInfo['index'] as int? ?? i;

        setState(() {
          _downloadedFiles = i;
          _currentFileName = fileName;
          _statusMessage = 'Downloading ${i + 1}/${files.length}: $fileName';
        });

        final downloadUri = Uri.parse('$baseUrl/p2p/download?t=$token&index=$fileIndex');
        final dlReq = await client.getUrl(downloadUri);
        final dlRes = await dlReq.close();

        if (dlRes.statusCode != 200) {
          debugPrint('Failed to download $fileName: HTTP ${dlRes.statusCode}');
          continue;
        }

        final destFile = File('${destDir.path}/$fileName');
        final sink = destFile.openWrite();
        await dlRes.cast<List<int>>().pipe(sink);

        debugPrint('✅ Downloaded: $fileName → ${destFile.path}');
      }

      setState(() {
        _downloadedFiles = files.length;
        _statusMessage = 'All files received!';
      });

      // Small delay for user to see completion
      await Future.delayed(const Duration(milliseconds: 500));
      widget.onComplete(files.length);
    } catch (e) {
      debugPrint('P2P receive error: $e');
      if (mounted) {
        setState(() {
          _errorMessage = e.toString().replaceFirst('Exception: ', '');
          _statusMessage = 'Transfer failed';
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      backgroundColor: LinLinkColors.surfaceContainer,
      title: Row(
        children: [
          Icon(
            _errorMessage != null ? Icons.error_outline : Icons.download_rounded,
            color: _errorMessage != null ? LinLinkColors.error : LinLinkColors.primary,
          ),
          const SizedBox(width: 8),
          Text(
            _errorMessage != null ? 'Transfer Failed' : 'Receiving Files',
            style: const TextStyle(fontSize: 16),
          ),
        ],
      ),
      content: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          if (_errorMessage != null) ...[
            Text(
              _errorMessage!,
              style: const TextStyle(color: LinLinkColors.error, fontSize: 13),
            ),
            const SizedBox(height: 12),
          ] else ...[
            if (_totalFiles > 0) ...[
              LinearProgressIndicator(
                value: _totalFiles > 0 ? _downloadedFiles / _totalFiles : null,
                backgroundColor: LinLinkColors.surfaceContainerLowest,
                color: LinLinkColors.primary,
              ),
              const SizedBox(height: 10),
            ] else ...[
              const LinearProgressIndicator(
                backgroundColor: LinLinkColors.surfaceContainerLowest,
                color: LinLinkColors.primary,
              ),
              const SizedBox(height: 10),
            ],
            Text(
              _statusMessage,
              style: const TextStyle(color: LinLinkColors.onSurfaceVariant, fontSize: 13),
            ),
            if (_currentFileName.isNotEmpty) ...[
              const SizedBox(height: 4),
              Text(
                _currentFileName,
                style: const TextStyle(
                  color: LinLinkColors.onSurface,
                  fontSize: 12,
                  fontWeight: FontWeight.w600,
                ),
                overflow: TextOverflow.ellipsis,
              ),
            ],
          ],
        ],
      ),
      actions: [
        if (_errorMessage != null) ...[
          TextButton(
            onPressed: widget.onCancel,
            child: const Text('Cancel'),
          ),
          FilledButton.icon(
            icon: const Icon(Icons.refresh, size: 16),
            label: const Text('Retry'),
            onPressed: _startReceiving,
          ),
        ],
      ],
    );
  }
}
